name: testing

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "master"
    
jobs:
  misspell:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Install misspell
      run: |
        go get -u github.com/client9/misspell/cmd/misspell
        
    - name: execute misspell
      run: |
        misspell .
 
  linting:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Install linter
      run: |
        go get -u golang.org/x/lint/golint
    - name: Execute linter
      run: |
        echo 'RESP<<EOF' >> $VAR
        golint >> $VAR
        echo 'EOF'
